config/routes.rb
Rails.application.routes.draw do
  resources :notes do 
      delete 'destroy_all', on: :collection
      put 'multiple_new', on: :collection
  end

  get '' => redirect('/notes')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true, length: { in: 1..100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit destroy update]

  def index
    @notes = Note.all
  end

  def show; end

  def new
    @note = Note.new
  end

  def multiple_new
    10.times { Note.create(title: "Sample Title", body: "Lorem ipsum ...") }
    redirect_to_root
  end

  def edit; end

  def update
    if @note.update(note_params)
      redirect_to_root
    else
      render "edit"
    end
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to_root
    else
      render "new"
    end
  end

  def destroy
    @note.destroy
    redirect_to_root
  end

  def destroy_all
    @note = Note.all
    @note.destroy_all
    redirect_to_root
  end

  private

  def note_params
    params.require(:note).permit(:title, :body)
  end

  def set_note
    @note = Note.find(params[:id])
  end

  def redirect_to_root
    redirect_to notes_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='app-header'>
      <h3 class='h3 zero-margin'>To-Do Rails App</h3>
    </div>

    <div class='dashboard'>
      <nav class='dashboard-navigation'>
        <ul class='list'>
            <li class='list-item'><%= link_to 'Add New', new_note_path, class: 'navigation-link' %></li>
            <li class='list-item'><%= link_to 'Add 10 Notes',multiple_new_notes_path, method: :put, data: { confirm: 'Are you sure?' }, class: 'navigation-link' %></li> 
            <li class='list-item'><%= link_to 'Delete All',destroy_all_notes_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'navigation-link' %></li> 
        </ul>
      </nav>
    <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_errors.html.haml
- if source.errors.any? 
  .errors-wrapper
    %h1.error-header
      Following your actions some errors appeard. They are listed below.
    %ul.errors-list
      - source.errors.full_messages.each do |msg|  
        %li.errors-list-item
          = msg 

app/views/notes/_form.html.haml
= form_with(model: note, local: true) do |form| 
  .note-form
    .title
      = form.text_area :title, placeholder: "Title", class: 'title' 
    .body       
      = form.text_area :body, placeholder: "Description", class: 'body' 
    %div
      = form.submit class: 'navigation-link submit' 
    

app/views/notes/edit.html.haml
= render 'errors', source: @note
.new-note
  %h1.h1
    Edit note

  = render 'form', note: @note

  %nav.navigation
    = link_to 'Back', notes_path, class: 'navigation-link' 

app/views/notes/index.html.haml
.dashboard-body
  %h2{:class => "h2 body-header"} Notes list
  %ul.dashboard-notes
    - @notes.each do |note|
      .note
        .h3
          = note.title   
        .body
          = note.body   
        %nav.navigation
          = link_to "Details", note, class: 'link'    
          = link_to 'Edit', edit_note_path(note.id), class: 'link'    
          = link_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link'    

app/views/notes/new.html.haml
= render 'errors', source: @note
.new-note
  %h1 New note
  = render 'form', note: @note

  %nav.navigation
    = link_to 'Back', notes_path, class: 'navigation-link'

app/views/notes/show.html.haml
.note-details
  .note
    %h2.h2
      = @note.title 
    %p{:class => 'body h3'}
      = @note.body 


    %nav.navigation
      = link_to 'Edit', edit_note_path(@note.id), class: 'link'  
      = link_to 'Delete', @note, method: :delete, data: { confirm: 'Are you sure?' }, class: 'link'  
      %p{:class => 'mute dates'}
        Date of creation: 
        = @note.created_at.to_s.at(0..19) 
      %p{:class => 'mute dates'}
        Last Update: 
        = @note.updated_at.to_s.at(0..19) 
  %nav.navigation
    = link_to 'Back', notes_path, class: 'navigation-link' 